# Generated by Django 3.2.2 on 2021-06-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsprojapplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
    ]
